update

diff --git a/.github/workflows/gitops-for-real-ci-cd-pipeline.yml b/.github/workflows/gitops-for-real-ci-cd-pipeline.yml
--- a/.github/workflows/gitops-for-real-ci-cd-pipeline.yml
+++ b/.github/workflows/gitops-for-real-ci-cd-pipeline.yml
@@ -18,136 +18,136 @@ env:
   
 
 jobs:
-  terraform-plan:
-    name: 'Terraform Plan'
-    runs-on: ubuntu-latest
+  # terraform-plan:
+  #   name: 'Terraform Plan'
+  #   runs-on: ubuntu-latest
     
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ${{ secrets.AWS_REGION }}
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_version: ${{ env.TERRAFORM_VERSION }}
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v3
+  #       with:
+  #         terraform_version: ${{ env.TERRAFORM_VERSION }}
 
         
 
-      - name: Terraform Init
-        run: |
-          terraform init \
-            -backend-config="bucket=${{ secrets.BACKEND_BUCKET }}" \
-            -backend-config="key=gitops-weather-app/${{ env.ENVIRONMENT }}/terraform.tfstate" \
-            -backend-config="region=${{ secrets.AWS_REGION }}" \
-            --reconfigure
-        working-directory: ${{ github.workspace }}/terraform
+  #     - name: Terraform Init
+  #       run: |
+  #         terraform init \
+  #           -backend-config="bucket=${{ secrets.BACKEND_BUCKET }}" \
+  #           -backend-config="key=gitops-weather-app/${{ env.ENVIRONMENT }}/terraform.tfstate" \
+  #           -backend-config="region=${{ secrets.AWS_REGION }}" \
+  #           --reconfigure
+  #       working-directory: ${{ github.workspace }}/terraform
 
-      - name: Terraform Plan
-        id: tf-plan      
-        run: |
-          export exitcode=0
-          terraform plan -detailed-exitcode -no-color -out=weather-app-tf.plan || export exitcode=$?
-          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-          if [ $exitcode -eq 1 ]; then
-            echo "Terraform Plan Failed!"
-            exit 1
-          fi
-        working-directory: ${{ github.workspace }}/terraform
+  #     - name: Terraform Plan
+  #       id: tf-plan      
+  #       run: |
+  #         export exitcode=0
+  #         terraform plan -detailed-exitcode -no-color -out=weather-app-tf.plan || export exitcode=$?
+  #         echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+  #         if [ $exitcode -eq 1 ]; then
+  #           echo "Terraform Plan Failed!"
+  #           exit 1
+  #         fi
+  #       working-directory: ${{ github.workspace }}/terraform
 
-      - name: Publish Terraform Plan
-        uses: actions/upload-artifact@v4
-        with:
-          name: weather-app-tf.plan
-          path: ${{ github.workspace }}/terraform
+  #     - name: Publish Terraform Plan
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: weather-app-tf.plan
+  #         path: ${{ github.workspace }}/terraform
           
 
-  terraform-apply:
-    name: 'Terraform Apply'
-    runs-on: ubuntu-latest
-    needs: [terraform-plan]
+  # terraform-apply:
+  #   name: 'Terraform Apply'
+  #   runs-on: ubuntu-latest
+  #   needs: [terraform-plan]
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ${{ secrets.AWS_REGION }}
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
-        with:
-          terraform_version: ${{ env.TERRAFORM_VERSION }} 
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v3
+  #       with:
+  #         terraform_version: ${{ env.TERRAFORM_VERSION }} 
 
-      - name: Terraform Init
-        run: |
-          terraform init \
-            -backend-config="bucket=${{ secrets.BACKEND_BUCKET }}" \
-            -backend-config="key=gitops-weather-app/${{ env.ENVIRONMENT }}/terraform.tfstate" \
-            -backend-config="region=${{ secrets.AWS_REGION }}" \
-            --reconfigure
-        working-directory: ${{ github.workspace }}/terraform
+  #     - name: Terraform Init
+  #       run: |
+  #         terraform init \
+  #           -backend-config="bucket=${{ secrets.BACKEND_BUCKET }}" \
+  #           -backend-config="key=gitops-weather-app/${{ env.ENVIRONMENT }}/terraform.tfstate" \
+  #           -backend-config="region=${{ secrets.AWS_REGION }}" \
+  #           --reconfigure
+  #       working-directory: ${{ github.workspace }}/terraform
 
-      - name: Download Terraform Plan
-        uses: actions/download-artifact@v4
-        with:
-          name: weather-app-tf.plan
-          path: ${{ github.workspace }}/terraform
+  #     - name: Download Terraform Plan
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: weather-app-tf.plan
+  #         path: ${{ github.workspace }}/terraform
 
       
-      - name: Apply Terraform Plan
-        run: terraform apply  -auto-approve  ${{ github.workspace }}/terraform/weather-app-tf.plan
-        working-directory: ${{ github.workspace }}/terraform
+  #     - name: Apply Terraform Plan
+  #       run: terraform apply  -auto-approve  ${{ github.workspace }}/terraform/weather-app-tf.plan
+  #       working-directory: ${{ github.workspace }}/terraform
 
-  docker-build-and-push:
-    name: 'Build and Push Docker Image'
-    runs-on: ubuntu-latest
-    steps:
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
+  # docker-build-and-push:
+  #   name: 'Build and Push Docker Image'
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v3
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+  #     - name: Login to Docker Hub
+  #       uses: docker/login-action@v3
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-        with:
-          token: ${{ secrets.REPO_TOKEN }}
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v4
+  #       with:
+  #         token: ${{ secrets.REPO_TOKEN }}
 
-      - name: Build and Push
-        uses: docker/build-push-action@v5
-        with:
-          push: true
-          context: .
-          file: Dockerfile            # # Capitalized filename "Dockerfile"
-          tags: ${{ secrets.DOCKERHUB_USERNAME }}/weather-app-backend-api:v${{ github.sha }}
-          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/weather-app-backend-api:cache
-          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/weather-app-backend-api:cache,mode=max
+  #     - name: Build and Push
+  #       uses: docker/build-push-action@v5
+  #       with:
+  #         push: true
+  #         context: .
+  #         file: Dockerfile            # # Capitalized filename "Dockerfile"
+  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/weather-app-backend-api:v${{ github.sha }}
+  #         cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/weather-app-backend-api:cache
+  #         cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/weather-app-backend-api:cache,mode=max
 
-      - name: Update Kubernetes Manifests
-        run: |
-          cd ./deployment
-          sed -i 's|image: .*$|image: ${{ secrets.DOCKERHUB_USERNAME }}/weather-app-backend-api:v${{ github.sha }}|' backend-api-deployment.yaml
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git commit -am "Update image tag to v${{ github.sha }}"
-          git push
+  #     - name: Update Kubernetes Manifests
+  #       run: |
+  #         cd ./deployment
+  #         sed -i 's|image: .*$|image: ${{ secrets.DOCKERHUB_USERNAME }}/weather-app-backend-api:v${{ github.sha }}|' backend-api-deployment.yaml
+  #         git config --local user.email "action@github.com"
+  #         git config --local user.name "GitHub Action"
+  #         git commit -am "Update image tag to v${{ github.sha }}"
+  #         git push
 
       
 
