update gha workflows yaml

diff --git a/.github/workflows/gitops-for-real-ci-cd-pipeline.yml b/.github/workflows/gitops-for-real-ci-cd-pipeline.yml
--- a/.github/workflows/gitops-for-real-ci-cd-pipeline.yml
+++ b/.github/workflows/gitops-for-real-ci-cd-pipeline.yml
@@ -48,18 +48,19 @@ jobs:
         working-directory: ./terraform
 
       - name: Terraform Plan
-        id: tf-plan
-        run: terraform plan -detailed-exitcode -no-color -out weather-app-tf.plan
-        working-directory: ./terraform  
+        id: tf-plan      
+        run: |
+          export exitcode=0
+          terraform plan -detailed-exitcode -no-color -out=weather-app-tf.plan || export exitcode=$?
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+          if [ $exitcode -eq 1 ]; then
+            echo "Terraform Plan Failed!"
+            exit 1
+          fi
+        working-directory: ./terraform
 
-      - name: Download plan and lock
-        uses: actions/download-artifact@v4
+      - name: Publish Terraform Plan
+        uses: actions/upload-artifact@v4
         with:
-          name: weather-app-tf.plan
+          name: weather-tf-plan
           path: ./terraform/weather-app-tf.plan
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          
-
-      - name: Restore Terraform lock file
-        run: cp ./terraform/.terraform.lock.hcl ./terraform/.terraform.lock.hcl  
-
